### ISSUE TITLE
Viewing individual classes shows a raw dump of prettify.js before showing the raw generated html

### ISSUE THREAD

**Issue by jamessheridan** [otiai10/jacoco-html-asset-bundle#2]
Hi. Thank you for this fantastic tool! 

We're using your tool to convert Java coverage reports for viewing in AzDO. All works great, apart from drilling down into each class to see which individual lines or functions are or aren't covered, when we get a raw output of what looks like a chunk of prettify.js before being intersected by the raw generated HTML of the classes.

Attached screenshots of what we're seeing. Any ideas?

![Screenshot 2020-08-18 at 11 24 13](https://user-images.githubusercontent.com/1038142/90550997-92328980-e145-11ea-9cad-53a335b451db.png)

![Screenshot 2020-08-18 at 11 36 23](https://user-images.githubusercontent.com/1038142/90552269-67493500-e147-11ea-8838-3813bb9150be.png)

**Comment by jamessheridan** [comment]
Uh, not sure where the arrow on the right came from on that 2nd screenshot. Pls ignore!

**Comment by otiai10** [comment]
Thank you for your feedback. I'll try to have a time with it.

**Comment by otiai10** [comment]
If you can, could you please provide a small example of raw `jacocoHTML` folder which can reproduce this problem.
@jamessheridan

**Comment by jamessheridan** [comment]
I'm trying to think of a way I can do that without, uh, sharing confidential source code that'll be present in the HTML output.

What do you need specifically?

**Comment by otiai10** [comment]
1. a raw HTML file
2. a resource directory

**Comment by davidtron** [comment]
I'm also seeing the same issue.  A brief inspection of one of the generated files shows that we inline some javascript that has a comment block which contains some script tags.  The first closing `</script>` breaks the markup of the page and results in the reported error (cant get it embedded properly here.

**Comment by otiai10** [comment]
Though it's a temp solution, I just published `jacoco-html-asset-bundle@0.2.1`. Happy if you guys can validate its behavior on your environment. Thank you!
https://www.npmjs.com/package/jacoco-html-asset-bundle

**Comment by jamessheridan** [comment]
Thank you for fixing this. I had kind of forgotten about the issue, sorry for not returning with an update.

Confirmed that this works for us in our Azure Devops environment.
